### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by tsinis** [ValentinVignal/action-dart-analyze#12]
Hey @ValentinVignal!

First of all - thanks for the great action! This issue is a follow-up of this [one](https://github.com/ValentinVignal/action-dart-analyze/issues/9). This is just a friendly reminder that, as the title and [GitHub Changelog](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20) say (so as warnings in our CIs) - `Node.js 16 actions are deprecated` :). Thanks again!

**Comment by ValentinVignal** [comment]
It should be fixed in the version 0.17 :)
