### ISSUE TITLE
Mention in the README that action checks only modified code

### ISSUE THREAD

**Issue by AndriyMatkivskiy** [ValentinVignal/action-dart-analyze#14]
hi @ValentinVignal 
Thanks for you amazing project.

The only thing that I was confused is that there is no mentions in the README.MD that this action only checks modified files in PR. 
I spent quite some time to figure out this. 😄 

Also to action to post comment in PR itself your `GITHUB_TOKEN` needs to have `pull_request: write` permission.

**Comment by ValentinVignal** [comment]
Thank you for the feedbacks @AndriyMatkivskiy . Sorry you lost time

Would you be interested in submitting a PR to update the documentation?
Otherwise, I'll do it 👍
