### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by calcitem** [ValentinVignal/action-dart-analyze#9]
Node.js 12 actions are deprecated. 

For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 

Please update the actions to use Node.js 16. 

Thanks!

**Comment by isAlmogK** [comment]
Following seems this is dead

**Comment by ValentinVignal** [comment]
Hello @isAlmogK What do you mean ? The github action is not working for you anymore ?

**Comment by isAlmogK** [comment]
Yes, getting that error and also its failing but when I run locally dart anlazie no issues

**Comment by ValentinVignal** [comment]
Ok, I'll try to release a new version using node 16 soon

**Comment by isAlmogK** [comment]
great, please update here thanks

**Comment by ValentinVignal** [comment]
@isAlmogK I've upgraded to node16 in the version `v0.15`

Use 

```yaml
uses: ValentinVignal/action-dart-analyze@v0.15
```

in your workflow file
